### ISSUE TITLE
Request Denied

### ISSUE THREAD

**Issue by PrakharPrashantSingh** [sanand0/geocode-excel#1]
My excel sheet is saying request denied on Geocoding, can u suggest any solution!

**Comment by sanand0** [comment]
Yeah, looks like either the free limit is removed or the API has changed.
Let me take a look this weekend Prashant

If you have any ideas, would be very glad for inputs please. Thanks!

**Comment by PrakharPrashantSingh** [comment]
Okay, This is a very fast reply, i wasn't expecting this fast!
Thank you sir

**Comment by zkenstein** [comment]
Any update on this?

**Comment by sanand0** [comment]
@zkenstein As with all weekends, that one flew past too quickly, and I wasn't able to solve the problem.

I *WAS* able to identify it. The API *has* changed. This will require 2-4 hours of time to solve, which is proving a little difficult.

However, I find that live-coding sessions help me prioritize. So if you or @PrakharPrashantSingh would like to join me for an hour, we can fix it together :-)

**Comment by PrakharPrashantSingh** [comment]
Hi @sanand0  sir, i didn't understood what you mean by " I find that live-coding sessions help me prioritize." but yes if there is anything in which i can contribute, i am ready!
Let me know what can i do....

**Comment by sanand0** [comment]
I've updated the function to accept a Google API key. It can also now use the Nominatim API which is free. Hope this helps!

Closed via 338b24b4
