### ISSUE TITLE
Does not work with German Umlauts

### ISSUE THREAD

**Issue by chrissi323** [sanand0/geocode-excel#2]
Hi,

just tried the Spreadsheet and it works as long as if there are no umlauts in the adress. I tried geocoding some german adresse and most of them failed because street is spelled Straße over here. Addresses located in Fürth also didn't work.

Is there a way to fix this?

Kind regards

Christian

**Comment by sanand0** [comment]
I'll release a version that fixes, @chrissi323 

![image](https://user-images.githubusercontent.com/63734/71774850-01cf7c00-2f9c-11ea-9af8-8e431c6a5b00.png)

But this requires Excel 2013 and above. Hope that's fine.

**Comment by chrissi323** [comment]
Hi,

works like a charm!

Thanks!

Christian
