### ISSUE TITLE
Upper limit of geocoding in Excel

### ISSUE THREAD

**Issue by Krukarius** [sanand0/geocode-excel#4]
Hi,

I just want to ask about the upper limit of geocoding in Excel.
For example, the Bing API can geocode up to 10k addresses from one account. 
How about the Nominatim. Is it limited at some point?
Thanks

**Comment by sanand0** [comment]
There doesn't seem to be an enforced rate limit. But [they ask](https://operations.osmfoundation.org/policies/nominatim/) that we keep it to light use, specifically 1 request per second.

Bulk-geocoding is also discouraged, unless

- it's a small task (often true in geocode-excel)
- limit your requests to a single thread (true in geocode-excel)
- limited to 1 machine only, no distributed scripts (including multiple Amazon EC2 instances or similar) (true in geocode-excel)
- Results must be cached on your side (not yet implemented in geocode-excel)
