### ISSUE TITLE
"The download of the specified resource has failed."

### ISSUE THREAD

**Issue by eightflat** [sanand0/geocode-excel#7]
Hello, when I try to reverse geocode using the _Nominatim_ function (`=NominatimReverseGeocode(lat, lng)`) I get the red text "The download of the specified resource has failed." 

![nx9FgTi](https://user-images.githubusercontent.com/42418384/160700959-4e0e06b7-ad6a-45df-b488-40dcfeb41dc5.png)

This appears to be the case with multiple legitimate latitude-longitude pairs. Normal geocoding (`=NominatimGeocode(address)`) works with no problem. Am I missing something obvious, or do you see anything obvious that has changed with the API or elsewhere? 

Thank you very much for your time developing this and for reading this :)

**Comment by sanand0** [comment]
The latest version fixes this issue @eightflat  -- thanks for raising it!
